services:
  - type: web
    name: price-list-manager
    env: static
    # Explicitly set the build command to do nothing to prevent Render from
    # auto-detecting a build step for this build-less project.
    buildCommand: "echo 'No build step required.'"
    # The root of the repository contains all the static files to be served.
    staticPublishPath: .
    headers:
      - path: "**/*.tsx"
        name: Content-Type
        value: text/javascript
      - path: "**/*.ts"
        name: Content-Type
        value: text/javascript
    routes:
      # Rewrite all requests to index.html to support client-side routing.
      - type: rewrite
        source: "/*"
        destination: "/index.html"